name: Reusable Workflow Example
on:
  push:
    branches: 'main'
  workflow_call:
    inputs:
      sonar_host:
        required:
        type: string
      environment:
        required: true
        type: string
      channel_id:
        required: true
        type: string
      job_status:
        required: true
        type: string
      github_actor:
        required: true
        type: string
      runner_os:
        required: true
        type: string
    secrets:
      SLACK_BOT_TOKEN:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: clone repo
        uses: actions/checkout@v4
      - name: environment
        run: |
          echo "${{ inputs.environment }} environment"
      - name: Sonar host
        run: |
          echo "Sonar url: ${{ inputs.sonar_host }}"
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv
          coverage: none
      - name: Installer les dependences
        run: composer install --prefer-dist --no-interaction --no-update
      - name: Copy file .env.exemple to .env
        run: cp .env.example .env
      - name: Generate key
        run: php artisan key:generate
      - name: Execution des tests
        run: |
            echo "Execution des tests"
      - name: Post to a Slack channel
        if: failure()
        id: slack
        uses: slackapi/slack-github-action@v1.25.0
        with:
          channel-id: ${{ inputs.channel_id }}
          slack-message: "GitHub build result: ${{ inputs.job_status }}\n${{ inputs.github_actor }}\n${{ inputs.runner_os }}"
        env:
          SLACK_BOT_TOKEN: 
            secrets:
              SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}


